defaults:
  - _self_
  - dataset: people_snapshot
  - pose_correction: direct
  - texture: shallow_mlp
  - rigid: skinning_field
  - non_rigid: hashgrid
  - option:
      - iter15k

hydra:
  run:
    dir: exp/${name}
  job:
    chdir: false

name: ${exp_dir}
tag: default
exp_dir: exp/h36m/s1
rigid_name: mlp_field

model:
  unet:
    delay: 5000

  gaussian:
    use_sh: false
    sh_degree: 3
    delay: 1000
    feature_dim: 32

  deformer:
    non_rigid:
      name: hashgrid
      scale_offset: logit
      rot_offset: mult
      delay: 3000
      feature_dim: ${model.texture.non_rigid_dim}
      latent_dim: 0
      pose_encoder:
        num_joints: 24
        rel_joints: false
        dim_per_joint: 6
        out_dim: -1

      hashgrid:
        n_levels: 16
        n_features_per_level: 2
        log2_hashmap_size: 16
        base_resolution: 16
        per_level_scale: 1.447269237440378 # max reso 4096
        max_resolution: 2048

      mlp:
        n_neurons: 128
        n_hidden_layers: 3
        skip_in: []
        cond_in: [ 0 ]
        multires: 0
        last_layer_init: false

    rigid:
      name: skinning_field
      distill: false
      res: 64
      z_ratio: 4
      d_out: 25
      soft_blend: 20
      n_reg_pts: 1024
      skinning_network:
        otype: VanillaMLP
        n_neurons: 128
        n_hidden_layers: 4
        skip_in: []
        cond_in: []
        multires: 0

  texture:
    name: mlp
    feature_dim: ${model.gaussian.feature_dim}
    use_xyz: false
    use_cov: false
    use_normal: false
    sh_degree: 3
    non_rigid_dim: 16
    latent_dim: 16
    cano_view_dir: true
    view_noise: 45
    mlp:
      n_neurons: 64
      n_hidden_layers: 2
      skip_in: []
      cond_in: []
      multires: 0

dataset:
  name: h36m
  preload: true
  train_smpl: false
  root_dir: "/data/zhaohaoyu/H36M/"
  subject: S8
  refine: false

  mode: ${mode}
  test_mode: view
  predict_seq: 0
  freeview: false

  train_views: [ '54138969', '55011271', '58860488' ]
  val_views: ['60457274']
  test_views:
    view: ${dataset.val_views}
    video: ['60457274']
    all: []
  predict_views: ['60457274']

  train_frames: [ 0, 500, 1]
  val_frames: [ 0, 1, 1 ]
  test_frames:
    view: [0, 500, 30]
    video: [0, 500, 1]
    all: [0, 500, 1]
  predict_frames: [0, 0, 1]

  img_hw:
    - 512
    - 512

  lanczos: false
  resolution: -1
  padding: 0.1
  white_background: false
  data_device: cuda
  eval: false


opt:

  coarse_iterations: 5000

  iterations: 15000
  grad_clip: 0.1

#  lambda_nr_xyz: 1e-2
  lambda_nr_xyz: 0.
#  lambda_nr_scale: 1e-4
  lambda_nr_scale: 0.
  lambda_nr_rot: 0.
  nr_latent_lr: 0.001
  unet_lr: 0.001
  lambda_xyz_noise: 0.001

  texture_lr: 0.001
  tex_latent_lr: 0.001
  latent_weight_decay: 0.05

  # learning rates
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.001
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001

  unet_lr: 0.001
  rigid_lr: 0.0001
  non_rigid_lr: 0.001
  lr_ratio: 0.1

  # loss weights
  lambda_l1: 1.
  lambda_dssim: 0.
  lambda_perceptual: 0.01
  mask_loss_type: l1
#  lambda_mask: [0.1,5000,0]
  lambda_mask: 0.1
  lambda_opacity: 0.
  lambda_skinning: [10,1000,0.1]
  lambda_aiap_xyz: 1.
  lambda_aiap_cov: 100.
  lambda_semantic: 0.01
  lambda_neighborhood: 0.1

  # densification configs
  percent_dense: 0.01
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 10000
  densify_grad_threshold: 0.0002
  opacity_threshold: 0.05

pipeline:
  convert_SHs_python: true
  compute_cov3D_python: true
  debug: false

#  pose_noise: 0.1
  xyz_noise: 0.01
#  texture_noise: 0.01

debug_from: -1
detect_anomaly: false
test_iterations: []
test_interval: 2000
save_iterations: [5000,10000]
seed: -1
checkpoint_iterations: [5000,10000]
start_checkpoint: null
wandb_disable: false

mode: train
load_ckpt: null
evaluate: true
clean: true